updated leiningen

diff --git a/bin/lein b/bin/lein
--- a/bin/lein
+++ b/bin/lein
@@ -1,14 +1,49 @@
-#!/bin/bash
+#!/bin/sh
 
-VERSION="1.1.0"
+export LEIN_VERSION="1.4.2"
 
-CLASSPATH="$(find lib/ -follow -mindepth 1 -maxdepth 1 -print0 2> /dev/null | tr \\0 \:)"
-LEIN_JAR="$HOME/.m2/repository/leiningen/leiningen/$VERSION/leiningen-$VERSION-standalone.jar"
-CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.1.0/clojure-1.1.0.jar"
+case $LEIN_VERSION in
+    *SNAPSHOT) SNAPSHOT="YES" ;;
+    *) SNAPSHOT="NO" ;;
+esac
+
+# Make sure classpath is in unix format for manipulating, then put
+# it back to windows format when we use it
+if [ "$OSTYPE" = "cygwin" ] && [ "$CLASSPATH" != "" ]; then
+    CLASSPATH=`cygpath -up $CLASSPATH`
+fi
+
+if [ "$USER" = "root" ] && [ "$LEIN_ROOT" = "" ]; then
+    echo "WARNING: You're currently running as root; probably by accident."
+    echo "Press control-C to abort or Enter to continue as root."
+    echo "Set LEIN_ROOT to disable this warning."
+    read
+fi
+
+ORIGINAL_PWD="$PWD"
+while [ ! -r "$PWD/project.clj" ] && [ "$PWD" != "/" ] && [ ! $NOT_FOUND ]
+do
+    cd ..
+    if [ "$(dirname "$PWD")" = "/" ]; then
+        NOT_FOUND=0
+        cd "$ORIGINAL_PWD"
+    fi
+done
+
+if [ "$LEIN_HOME" = "" ]; then
+    LEIN_HOME="$HOME/.lein"
+fi
+
+LEIN_PLUGINS="$(ls -1 lib/dev/*jar 2> /dev/null | tr \\n \:)"
+LEIN_USER_PLUGINS="$(ls -1 $LEIN_HOME/plugins/*jar 2> /dev/null | tr \\n \:)"
+CLASSPATH=$LEIN_USER_PLUGINS:$LEIN_PLUGINS:test/:src/:$CLASSPATH
+LEIN_JAR="$HOME/.lein/self-installs/leiningen-$LEIN_VERSION-standalone.jar"
+CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.2.0/clojure-1.2.0.jar"
+NULL_DEVICE=/dev/null
 
 # normalize $0 on certain BSDs
-if [ "$(dirname $0)" = "." ]; then
-    SCRIPT="$(which $(basename $0))"
+if [ "$(dirname "$0")" = "." ]; then
+    SCRIPT="$(which $(basename "$0"))"
 else
     SCRIPT="$0"
 fi
@@ -20,7 +55,7 @@ while [ -h "$SCRIPT" ] ; do
     if expr "$link" : '/.*' > /dev/null; then
         SCRIPT="$link"
     else
-        SCRIPT="`dirname "$SCRIPT"`/$link"
+        SCRIPT="$(dirname "$SCRIPT"$)/$link"
     fi
 done
 
@@ -30,12 +65,10 @@ if [ -r "$BIN_DIR/../src/leiningen/core.clj" ]; then
     # Running from source checkout
     LEIN_DIR="$(dirname "$BIN_DIR")"
     LEIN_LIBS="$(find -H $LEIN_DIR/lib -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
-    CLASSPATH="$LEIN_DIR/src:$LEIN_LIBS:$CLASSPATH"
+    CLASSPATH="$LEIN_LIBS:$CLASSPATH:$LEIN_DIR/src:$LEIN_DIR/resources:$LEIN_JAR"
 
-    if [ "$LEIN_LIBS" = "" -a "$1" != "self-install" ]; then
-        echo "Your Leiningen development checkout is missing its dependencies."
-        echo "Please download a stable version of Leiningen to fetch the deps."
-        echo "See the \"Hacking\" section of the readme for details."
+    if [ "$LEIN_LIBS" = "" -a "$1" != "self-install" -a ! -r "$LEIN_JAR" ]; then
+        echo "Leiningen is missing its dependencies. Please see \"Building\" in the README."
         exit 1
     fi
 else
@@ -43,47 +76,38 @@ else
     CLASSPATH="$LEIN_JAR:$CLASSPATH"
 
     if [ ! -r "$LEIN_JAR" -a "$1" != "self-install" ]; then
-        echo "Leiningen is not installed. Please run \"lein self-install\"."
-        exit 1
+        "$0" self-install
     fi
 fi
 
-if [ $DEBUG ]; then
-    echo $CLASSPATH
-fi
-
-# escape command-line arguments so they can be evaled as strings
-ESCAPED_ARGS=""
-for ARG in "$@"; do
-  ESCAPED_ARGS="$ESCAPED_ARGS"' "'$(echo $ARG | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')'"'
-done
-
-HTTP_CLIENT="wget -O"
+HTTP_CLIENT="wget --no-check-certificate -O"
 if type -p curl >/dev/null 2>&1; then
-    HTTP_CLIENT="curl -L -o"
+    HTTP_CLIENT="curl --insecure -f -L -o"
 fi
 
-if [ "$1" = "repl" ]; then
-    if [ -r project.clj ]; then
-        echo "Warning: the repl task currently doesn't honor some project.clj"
-        echo "options due to I/O stream issues. Future versions will address"
-        echo "this, but for now you will get more consistent behaviour from repls"
-        echo "launched by either the lein-swank plugin or the lein-nailgun plugin."
-        echo
-    fi
-    $RLWRAP java -client $JAVA_OPTS -cp "src/:classes/:$CLASSPATH" jline.ConsoleRunner clojure.main ${@:2}
-elif [ "$1" = "self-install" ]; then
-    if [[ $VERSION == *SNAPSHOT ]]; then
-        echo "The self-install task is only meant for stable releases."
-        echo "See the \"Hacking\" section of the README."
+JAVA_CMD=${JAVA_CMD:-"java"}
+
+# Support $JAVA_OPTS for backwards-compatibility.
+JVM_OPTS=${JVM_OPTS:-$JAVA_OPTS}
+
+# If you're packaging this for a package manager (.deb, homebrew, etc)
+# you need to remove the self-install and upgrade functionality.
+if [ "$1" = "self-install" ]; then
+    echo "Downloading Leiningen now..."
+    LEIN_DIR=`dirname "$LEIN_JAR"`
+    mkdir -p "$LEIN_DIR"
+    LEIN_URL="https://github.com/downloads/technomancy/leiningen/leiningen-$LEIN_VERSION-standalone.jar"
+    $HTTP_CLIENT "$LEIN_JAR" "$LEIN_URL"
+    if [ $? != 0 ]; then
+        echo "Failed to download $LEIN_URL"
+        if [ $SNAPSHOT = "YES" ]; then
+            echo "See README.md for SNAPSHOT build instructions."
+        fi
+        rm $LEIN_JAR 2> /dev/null
         exit 1
     fi
-    echo "Downloading Leiningen now..."
-    mkdir -p `dirname "$LEIN_JAR"`
-    LEIN_URL="http://github.com/downloads/technomancy/leiningen/leiningen-$VERSION-standalone.jar"
-    exec $HTTP_CLIENT "$LEIN_JAR" "$LEIN_URL"
 elif [ "$1" = "upgrade" ]; then
-    if [[ $VERSION == *SNAPSHOT ]]; then
+    if [ $SNAPSHOT = "YES" ]; then
         echo "The upgrade task is only meant for stable releases."
         echo "See the \"Hacking\" section of the README."
         exit 1
@@ -99,7 +123,7 @@ elif [ "$1" = "upgrade" ]; then
             y|Y|"")
                 echo
                 echo "Upgrading..."
-                LEIN_SCRIPT_URL="http://github.com/technomancy/leiningen/raw/stable/bin/lein"
+                LEIN_SCRIPT_URL="https://github.com/technomancy/leiningen/raw/stable/bin/lein"
                 $HTTP_CLIENT "$SCRIPT" "$LEIN_SCRIPT_URL" \
                     && chmod +x "$SCRIPT" \
                     && echo && $SCRIPT self-install && echo && echo "Now running" `$SCRIPT version`
@@ -110,5 +134,42 @@ elif [ "$1" = "upgrade" ]; then
         esac
     fi
 else
-    exec java -Xbootclasspath/a:"$CLOJURE_JAR" -client $JAVA_OPTS -cp "$CLASSPATH" -Dleiningen.version="$VERSION" clojure.main -e "(use 'leiningen.core)(-main $ESCAPED_ARGS)"
+    if [ "$OSTYPE" = "cygwin" ]; then
+        # When running on Cygwin, use Windows-style paths for java
+        CLOJURE_JAR=`cygpath -w "$CLOJURE_JAR"`
+        ORIGINAL_PWD=`cygpath -w "$ORIGINAL_PWD"`
+        CLASSPATH=`cygpath -wp "$CLASSPATH"`
+        NULL_DEVICE=NUL
+    fi
+
+    if [ $DEBUG ]; then
+        echo $CLASSPATH
+        echo $CLOJURE_JAR
+    fi
+
+    JLINE=""
+    if ([ "$1" = "repl" ] || [ "$1" = "interactive" ] || [ "$1" = "int" ]) &&
+        [ -z $INSIDE_EMACS ] && [ "$TERM" != "dumb" ]; then
+        # Use rlwrap if it's available, otherwise fall back to JLine
+        RLWRAP=`which rlwrap`
+        if [ ! -x "$RLWRAP" ] || [ "$RLWRAP" = "" ]; then
+            RLWRAP=""
+            JLINE=jline.ConsoleRunner
+            if [ "$OSTYPE" = "cygwin" ]; then
+                JLINE="-Djline.terminal=jline.UnixTerminal jline.ConsoleRunner"
+                CYGWIN_JLINE=y
+            fi
+        fi
+    fi
+
+    # The -Xbootclasspath argument is optional here: if the jar
+    # doesn't exist everything will still work, it will just have a
+    # slower JVM boot.
+    # TODO: add more to the boot classpath
+    test $CYGWIN_JLINE && stty -icanon min 1 -echo
+    exec $RLWRAP $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client $JVM_OPTS \
+        -Dleiningen.original.pwd="$ORIGINAL_PWD" \
+        -cp "$CLASSPATH" $JLINE clojure.main -e "(use 'leiningen.core)(-main)" \
+        $NULL_DEVICE $@
+    test $CYGWIN_JLINE && stty icanon echo
 fi
